# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
     - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
